# Changes here will be overwritten by Copier
_commit: 2024.08.29
_src_path: gh:zenml-io/template-e2e-batch
data_quality_checks: true
email: ''
full_name: Tom Sawyer
hyperparameters_tuning: true
metric_compare_promotion: true
notify_on_failures: true
notify_on_successes: true
open_source_license: apache
product_name: e2e_use_case
project_name: Handwriting Recognition System
target_environment: production
version: 0.0.1
zenml_server_url: ''
